<div class='np-project-box-row'>
<A HREF='np_epoc'>
<div class="np-project-box" style="background-image: url('np_epoc/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>np_epoc
</p>
  </div>
  <div class="np-project-box-description">
    <p>Max/Pd external for the Emotiv EPOC EEG
</p>
  </div>
</div>
</A>

<A HREF='np_lightstone'>
<div class="np-project-box" style="background-image: url('np_lightstone/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>np_lightstone
</p>
  </div>
  <div class="np-project-box-description">
    <p>Max/Pd External for the Lightstone Biometrics Widget
</p>
  </div>
</div>
</A>

<A HREF='np_mindset'>
<div class="np-project-box" style="background-image: url('np_mindset/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>np_mindset
</p>
  </div>
  <div class="np-project-box-description">
    <p>Max/Pd External for the Neurosky Mindset EEG
</p>
  </div>
</div>
</A>

<A HREF='np_nifalcon'>
<div class="np-project-box" style="background-image: url('np_nifalcon/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>np_nifalcon
</p>
  </div>
  <div class="np-project-box-description">
    <p>Max/Pd external for the Novint Falcon Haptic Device
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='np_thirdspacevest'>
<div class="np-project-box" style="background-image: url('np_thirdspacevest/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>np_thirdspacevest
</p>
  </div>
  <div class="np-project-box-description">
    <p>Max/Pd External for the Third Space Vest Haptic Device
</p>
  </div>
</div>
</A>

<A HREF='np_trancevibe'>
<div class="np-project-box" style="background-image: url('np_trancevibe/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>np_trancevibe
</p>
  </div>
  <div class="np-project-box-description">
    <p>Max/Pd External for Rez Trance Vibrator compatible vibes
</p>
  </div>
</div>
</A>
</div>