<div class='np-project-box-row'>
<A HREF='emokit'>
<div class="np-project-box" style="background-image: url('emokit/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Emokit
</p>
  </div>
  <div class="np-project-box-description">
    <p>Driver for the Emotiv EPOC EEG
</p>
  </div>
</div>
</A>

<A HREF='openkinect'>
<div class="np-project-box" style="background-image: url('openkinect/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>OpenKinect
</p>
  </div>
  <div class="np-project-box-description">
    <p>Driver for Microsoft Kinect Camera
</p>
  </div>
</div>
</A>

<A HREF='libambx'>
<div class="np-project-box" style="background-image: url('libambx/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>libambx
</p>
  </div>
  <div class="np-project-box-description">
    <p>Cross platform driver for the Ambx environment system
</p>
  </div>
</div>
</A>

<A HREF='libfitbit'>
<div class="np-project-box" style="background-image: url('libfitbit/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>libfitbit
</p>
  </div>
  <div class="np-project-box-description">
    <p>Driver for the Fitbit pedometer
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='liblightstone'>
<div class="np-project-box" style="background-image: url('liblightstone/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>liblightstone
</p>
  </div>
  <div class="np-project-box-description">
    <p>Cross platform driver for the Lightstone biometrics widget
</p>
  </div>
</div>
</A>

<A HREF='libnifalcon'>
<div class="np-project-box" style="background-image: url('libnifalcon/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>libnifalcon
</p>
  </div>
  <div class="np-project-box-description">
    <p>Cross platform driver for the Novint Falcon
</p>
  </div>
</div>
</A>

<A HREF='libomron'>
<div class="np-project-box" style="background-image: url('libomron/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>libomron
</p>
  </div>
  <div class="np-project-box-description">
    <p>Driver for omron pedometer and bp monitor
</p>
  </div>
</div>
</A>

<A HREF='libthirdspacevest'>
<div class="np-project-box" style="background-image: url('libthirdspacevest/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>libthirdspacevest
</p>
  </div>
  <div class="np-project-box-description">
    <p>Driver for the Third Space Vest haptic device
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='libtrancevibe'>
<div class="np-project-box" style="background-image: url('libtrancevibe/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>libtrancevibe
</p>
  </div>
  <div class="np-project-box-description">
    <p>Driver for Rez Trancevibrator protocol compatible vibrators
</p>
  </div>
</div>
</A>
</div>