<div class='np-project-box-row'>
<A HREF='g4-proving-grounds-kinect'>
<div class="np-project-box" style="background-image: url('g4-proving-grounds-kinect/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Proving Grounds Kinect Stunt
</p>
    <p>2011
</p>
  </div>
  <div class="np-project-box-description">
    <p>Kinect control for G4TV's Proving Grounds Star Wars Stunt
</p>
  </div>
</div>
</A>

<A HREF='omron-shape-up-the-nation'>
<div class="np-project-box" style="background-image: url('omron-shape-up-the-nation/web/small.jpg')">
  <div class="np-project-box-title">
    <p>SUTN Omron Client
</p>
    <p>2009
</p>
  </div>
  <div class="np-project-box-description">
    <p>Pedometer info upload client for Shape Up The Nation
</p>
  </div>
</div>
</A>

<A HREF='marte'>
<div class="np-project-box" style="background-image: url('marte/web/small.jpg')">
  <div class="np-project-box-title">
    <p>CSHS Controls for MARTE Drill
</p>
    <p>2005
</p>
  </div>
  <div class="np-project-box-description">
    <p>Controls for Core Sample Handling System for MARTE Drill
</p>
  </div>
</div>
</A>

<A HREF='xbc-firmware'>
<div class="np-project-box" style="background-image: url('xbc-firmware/web/small.jpg')">
  <div class="np-project-box-title">
    <p>XBC Firmware
</p>
    <p>2004
</p>
  </div>
  <div class="np-project-box-description">
    <p>Firmware/GUI for Xport Botball Controller
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='copernicus-rover'>
<div class="np-project-box" style="background-image: url('copernicus-rover/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Copernicus Rover
</p>
    <p>2004
</p>
  </div>
  <div class="np-project-box-description">
    <p>Research rover for Copernicus Mission proposal. 
</p>
  </div>
</div>
</A>

<A HREF='interactive-c'>
<div class="np-project-box" style="background-image: url('interactive-c/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Interactive C
</p>
    <p>2003-2006
</p>
  </div>
  <div class="np-project-box-description">
    <p>Interactive C Compiler for educational robotics platforms
</p>
  </div>
</div>
</A>
</div>