<div class='np-project-box-row'>
<A HREF='keepon-kinect-control'>
<div class="np-project-box" style="background-image: url('keepon-kinect-control/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Keepon Kinect Control
</p>
    <p>2011
</p>
  </div>
  <div class="np-project-box-description">
    <p>Controlling a reverse engineered MyKeepon bot using the Microsoft
Kinect
</p>
  </div>
</div>
</A>

<A HREF='pen15-board'>
<div class="np-project-box" style="background-image: url('pen15-board/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Pen15 Board
</p>
    <p>2011
</p>
  </div>
  <div class="np-project-box-description">
    <p>Vibrator control shield for the Arduino
</p>
  </div>
</div>
</A>

<A HREF='missing-a-kick'>
<div class="np-project-box" style="background-image: url('missing-a-kick/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Missing a Kick
</p>
    <p>2010
</p>
  </div>
  <div class="np-project-box-description">
    <p>SL Art Piece with Wiimote triggering
</p>
  </div>
</div>
</A>

<A HREF='sex-toy-workshop'>
<div class="np-project-box" style="background-image: url('sex-toy-workshop/web/small.jpg')">
  <div class="np-project-box-title">
    <p>DIY Sex Toy Workshop
</p>
    <p>2010
</p>
  </div>
  <div class="np-project-box-description">
    <p>Workshop for building arduino based vibrators
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='drink-serving-bot'>
<div class="np-project-box" style="background-image: url('drink-serving-bot/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Drink Bot/Bartris/Adult Mario
</p>
    <p>2009
</p>
  </div>
  <div class="np-project-box-description">
    <p>Drink mixer with video game controls
</p>
  </div>
</div>
</A>

<A HREF='deldo'>
<div class="np-project-box" style="background-image: url('deldo/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Deldo
</p>
    <p>2009
</p>
  </div>
  <div class="np-project-box-description">
    <p>Sex Toy Control and Teledildonics mode for emacs
</p>
  </div>
</div>
</A>

<A HREF='biometric-presentation'>
<div class="np-project-box" style="background-image: url('biometric-presentation/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Biometric Presentation
</p>
    <p>2009
</p>
  </div>
  <div class="np-project-box-description">
    <p>Presentation software that displays biometrics of presenter
</p>
  </div>
</div>
</A>

<A HREF='a-day-at-the-ports'>
<div class="np-project-box" style="background-image: url('a-day-at-the-ports/web/small.jpg')">
  <div class="np-project-box-title">
    <p>A Day at the Ports
</p>
    <p>2009
</p>
  </div>
  <div class="np-project-box-description">
    <p>iPhone film pieces with generative audio
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='fc-2009-point-cloud'>
<div class="np-project-box" style="background-image: url('fc-2009-point-cloud/web/small.jpg')">
  <div class="np-project-box-title">
    <p>FC 2009 Point Cloud
</p>
    <p>2009
</p>
  </div>
  <div class="np-project-box-description">
    <p>3D Point Cloud of 512 Fursuits
</p>
  </div>
</div>
</A>

<A HREF='kitelight'>
<div class="np-project-box" style="background-image: url('kitelight/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Kitelight
</p>
    <p>2008
</p>
  </div>
  <div class="np-project-box-description">
    <p>Wireless lighting control system for kites
</p>
  </div>
</div>
</A>

<A HREF='reztunes'>
<div class="np-project-box" style="background-image: url('reztunes/web/small.jpg')">
  <div class="np-project-box-title">
    <p>RezTunes
</p>
    <p>2008
</p>
  </div>
  <div class="np-project-box-description">
    <p>iTunes plugin for audio activation of Rez Trancevibrator
</p>
  </div>
</div>
</A>

<A HREF='wiiyo'>
<div class="np-project-box" style="background-image: url('wiiyo/web/small.jpg')">
  <div class="np-project-box-title">
    <p>WiiYo
</p>
    <p>2008
</p>
  </div>
  <div class="np-project-box-description">
    <p>Yoyo tracking via Wiimote IR Camera
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='twittercore'>
<div class="np-project-box" style="background-image: url('twittercore/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Twittercore
</p>
    <p>2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>Generative breakcore based on twitter messages
</p>
  </div>
</div>
</A>

<A HREF='moaning-lisa'>
<div class="np-project-box" style="background-image: url('moaning-lisa/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Moaning Lisa
</p>
    <p>2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>Interactive mannequin as sexual interface
</p>
  </div>
</div>
</A>

<A HREF='trettio-lighting-system'>
<div class="np-project-box" style="background-image: url('trettio-lighting-system/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Trettio Lighting System
</p>
    <p>2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>USB control system for Ikea Trettio light set
</p>
  </div>
</div>
</A>

<A HREF='force-feedback-reality'>
<div class="np-project-box" style="background-image: url('force-feedback-reality/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Force Feedback Reality
</p>
    <p>2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>Sensor system for triggering vibration via surrounding environment
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='fwiktr'>
<div class="np-project-box" style="background-image: url('fwiktr/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Fwiktr
</p>
    <p>2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>Matching twitter captions and flickr images for generative art
</p>
  </div>
</div>
</A>

<A HREF='twitterdildonics'>
<div class="np-project-box" style="background-image: url('twitterdildonics/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Twitterdildonics
</p>
    <p>2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>Using twitter messages to trigger vibration
</p>
  </div>
</div>
</A>

<A HREF='electric-slide-lawsuit'>
<div class="np-project-box" style="background-image: url('electric-slide-lawsuit/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Electric Slide Lawsuit
</p>
    <p>2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>DMCA lawsuit over video of a line dance performance
</p>
  </div>
</div>
</A>

<A HREF='lifecycle'>
<div class="np-project-box" style="background-image: url('lifecycle/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Lifecycle
</p>
    <p>2005
</p>
  </div>
  <div class="np-project-box-description">
    <p>Driving Second Life vehicles via exercise bike
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='eyesore'>
<div class="np-project-box" style="background-image: url('eyesore/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Eyesore Projection System
</p>
    <p>2005

</p>
  </div>
  <div class="np-project-box-description">
    <p>Real Time 3D Viewing setup for Second Life
</p>
  </div>
</div>
</A>

<A HREF='second-life-teledildonics'>
<div class="np-project-box" style="background-image: url('second-life-teledildonics/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Second Life Teledildonics
</p>
    <p>2005
</p>
  </div>
  <div class="np-project-box-description">
    <p>Sex toy control via Second Life
</p>
  </div>
</div>
</A>

<A HREF='exercise-bike-nibbles'>
<div class="np-project-box" style="background-image: url('exercise-bike-nibbles/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Snake Game for Exercise Bike
</p>
    <p>2005
</p>
  </div>
  <div class="np-project-box-description">
    <p>Snake video game with Exercise Bike control
</p>
  </div>
</div>
</A>

<A HREF='sexbox'>
<div class="np-project-box" style="background-image: url('sexbox/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Sexbox
</p>
    <p>2005
</p>
  </div>
  <div class="np-project-box-description">
    <p>Rewiring Xbox feedback to sex toys
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='qengine'>
<div class="np-project-box" style="background-image: url('qengine/web/small.jpg')">
  <div class="np-project-box-title">
    <p>qEngine
</p>
    <p>2002
</p>
  </div>
  <div class="np-project-box-description">
    <p>Small DirectX based game engine
</p>
  </div>
</div>
</A>

<A HREF='ppc-mancala'>
<div class="np-project-box" style="background-image: url('ppc-mancala/web/small.jpg')">
  <div class="np-project-box-title">
    <p>Mancala for Pocket PC
</p>
    <p>1999
</p>
  </div>
  <div class="np-project-box-description">
    <p>Small mancala game for Windows CE 2
</p>
  </div>
</div>
</A>
</div>