<div class='np-project-box-row'>
<A HREF='openyou'>
<div class="np-project-box" style="background-image: url('openyou/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>OpenYou.org
</p>
    <p>2011-Present
</p>
  </div>
  <div class="np-project-box-description">
    <p>Reverse engineering health and medical devices
</p>
  </div>
</div>
</A>

<A HREF='opendildonics'>
<div class="np-project-box" style="background-image: url('opendildonics/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>OpenDildonics
</p>
    <p>2007-Present
</p>
  </div>
  <div class="np-project-box-description">
    <p>Wiki for information on sex technology and DIY projects
</p>
  </div>
</div>
</A>

<A HREF='mmorgy'>
<div class="np-project-box" style="background-image: url('mmorgy/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>MMOrgy
</p>
    <p>2005-2007
</p>
  </div>
  <div class="np-project-box-description">
    <p>Blog about sex in Massively Multiplayer Online Games
</p>
  </div>
</div>
</A>

<A HREF='deathbots'>
<div class="np-project-box" style="background-image: url('deathbots/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Deathbots
</p>
    <p>2004-2005
</p>
  </div>
  <div class="np-project-box-description">
    <p>Robotics news/projects blog
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='slashdong'>
<div class="np-project-box" style="background-image: url('slashdong/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Slashdong
</p>
    <p>2004-Present
</p>
  </div>
  <div class="np-project-box-description">
    <p>Sex Technology blog and project site 
</p>
  </div>
</div>
</A>

<A HREF='nonpolynomial'>
<div class="np-project-box" style="background-image: url('nonpolynomial/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Nonpolynomial Labs
</p>
    <p>2004-Present
</p>
  </div>
  <div class="np-project-box-description">
    <p>Personal/Project/Company website
</p>
  </div>
</div>
</A>

<A HREF='ia1hacking'>
<div class="np-project-box" style="background-image: url('ia1hacking/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>IA1 Hacking
</p>
    <p>2002-2004
</p>
  </div>
  <div class="np-project-box-description">
    <p>Information about hacking the Compaq IA1 Internet Appliance
</p>
  </div>
</div>
</A>

<A HREF='numberporn'>
<div class="np-project-box" style="background-image: url('numberporn/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Numberporn
</p>
    <p>2001-2004
</p>
  </div>
  <div class="np-project-box-description">
    <p>Personal blog
</p>
  </div>
</div>
</A>
</div><div class='np-project-box-row'>
<A HREF='gothicscouts'>
<div class="np-project-box" style="background-image: url('gothicscouts/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Gothic Scouts
</p>
    <p>1997-2003
</p>
  </div>
  <div class="np-project-box-description">
    <p>Gothic humor site turned social network
</p>
  </div>
</div>
</A>

<A HREF='boredgothcentral'>
<div class="np-project-box" style="background-image: url('boredgothcentral/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Bored Goth Central
</p>
    <p>1995-2000
</p>
  </div>
  <div class="np-project-box-description">
    <p>Goth project website
</p>
  </div>
</div>
</A>

<A HREF='mageswwwpage'>
<div class="np-project-box" style="background-image: url('mageswwwpage/web/icon.jpg')">
  <div class="np-project-box-title">
    <p>Mage's WWW Page
</p>
    <p>1994-1995
</p>
  </div>
  <div class="np-project-box-description">
    <p>My first website
</p>
  </div>
</div>
</A>
</div>